config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'events#index'
  resources :users
  resources :charges
  resources :attendances
  resources :template

  resources :events do
    resources :avatars, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  belongs_to :user
  belongs_to :event

  def att_event
    @events = Event.event_to_att
end

end

app/models/event.rb
class Event < ApplicationRecord

  #def attend_to_event_send
   # UserMailer.attend_to_event_email(self).deliver_now
  #end

  #def self.event_to_att
  #end

  has_one_attached :avatar

  has_many :attendances
  has_many :users, through: :attendances

  belongs_to :admin, class_name: 'User' #, optional: true
  has_many :attendances
  has_many :users, through: :attendances

  

  validates :duration, presence: true
  #multiple de 5? 
  validates :description, presence: true, length: {minimum: 20, maximum: 1000}
  validates :price, presence: true
  validates :location, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  

  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
 
  has_many :events, through: :attendances
  has_many :attendances
  has_many :events, foreign_key: 'admin_id', class_name: 'Event'

  #after_create :welcome_send

  #def welcome_send
   # UserMailer.welcome_email(self).deliver_now
  #end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def index
    @events = Event.find(params[:id])
    @attendances = @events.attendances
    unless current_user == @event.admin
      flash[:failure] = "Not authorized"
      redirect_to root_path
    end
  end

  def new
    @attendances = Attendance.all
    @event = Event.find(params[:id])
  end

  def create
    @attendances = Attendance.new(user_id: params[:user_id], event_id: params[:event_id], stripe_customer_id: params[:customer_id])

    if @attendances.save
      flash[:success] = "Event registration successfully saved"
      redirect_to root_path
    else
      flash[:error] = "Event registration saving failed"
      redirect_to root_path
    end
  end
private

  def attendance_params
    params.permit(:event_id, :user_id, :stripe_customer_id)
  end

end

app/controllers/avatars_controller.rb
class AvatarsController < ApplicationController
  def create
    @events = Event.find(params[:event_id])
    @events.avatar.attach(params[:avatar])
    redirect_to(event_path(@events))
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @event = Event.find(params[:id])
  end
  
  def create
    @event = Event.find(params[:id])
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'usd',
    })
  
    @customer_id = customer.id
    
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def index
    @events = Event.all
  end 

  def show
    @events = Event.find(params[:id])
  end 

  def new
    @events = Event.new
  end 

  def create
    @events = Event.new(event_params)
    puts @events.title
    if @events.save
      flash[:success] = "Votre évènement vient d'être créé ! "
      redirect_to event_path(@events.id)
    else
      messages = []
      if @events.errors.any? 
        @events.errors.full_messages.each do |message| 
          messages << message
        end 
        flash[:error] = "Votre évènement n'a pas pu être créé pour les raisons suivantes : #{messages.join(" ")}"
        render 'new'
      end
    end
  end

  def update
    @event = Event.find(params[:id])
    #if !current_user?(@event.admin)
    #  flash[:error] = "You are the wrong user."
    #  redirect_to root_path
    #else
      if @event.update(event_update)
        flash[:success] = "Your event has been updated."
        redirect_to event_path(@event.id)
      else
        render 'edit'
      end
    #end
  end
private

  def event_params
  params.require(:events).permit(:title, :location, :duration, :description, :price, :start_date, :admin_id)
  end

  def event_update
    params.require(:event).permit(:title, :location, :duration, :description, :price, :start_date)
  end

end
     

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    log_out(current_user)
    flash[:danger] = 'Vous vous êtes déconnectés.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!, only: [:show, :edit, :update]
  #before_action :own_profil

  def index
    @users = User.all
  end

  def new 
    @users = User.new
  end

  def edit
    @users = User.find(params[:id])
  end


  #def authenticate_user
   # unless current_user
      
    #  redirect_to new_user_session_path
    #end
  #end

  #def own_profil
   # if current_user.id == params[:id]
     
    #  redirect_to new_user_session_path
   # end
  #end


  def update
    @users = User.find(params[:id])
      if @users.update(user_params)
        flash[:success] = "Ton profil a été mis-à-jour."
        redirect_to user_path(@users.id)
      else
        render 'edit'
      end
    end



  
  def show
    @events_user = User.find(params[:id]).events
    @users = User.find(params[:id])
        if current_user.id != @users.id
            flash[:error] = "You are not the allowed."
          redirect_to root_path
        end
end

private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :description)
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
  
 
  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
  
end

app/helpers/avatars_helper.rb
module AvatarsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
  def current_user?(users)
    users == current_user.id
  end

  def event_title
    Event.find_by(:title)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
end

app/helpers/templates_helper.rb
module TemplatesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def current_user?(users)
    users == current_user.id
  end

end

app/views/attendances/index.html.erb
<h1><% @event.attendances.count%> = nombres de participants</h1>

<%= link_to "Revenir à l'accueil", events_path, class: "mt-2 btn btn-dark text-light text-center" %>

app/views/attendances/new.html.erb
<br>
<div class="row justify-content-center">
 <h3> Participer à l'event <%= @event.title %> </span></h3>
</div>

<br>

<div class="jumbotron jumbo_img">

  <div class="row justify-content-center">
    <div class="card" style="width: 30rem;">
      <div class="card-header text-center">
      <br>
      <h2> Vos informations</h2>
 <div class="container">
  <div class="card border-0 shadow my-5">
   <div class="card-body p-5">
   

 

  
  <div class="card" style="width: 20rem;">
  <div class="card-header">
   ID : <%= current_user.id %>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item">Email : <%= current_user.email %></li>
    <li class="list-group-item">Prénom : <%= current_user.first_name %> </li>
    <li class="list-group-item">Nom : <%= current_user.last_name %> </li>
    
  </ul>
</div>
</div>
</div>


    <div class="row justify-content-center">
     <label class="amount">
      <div class="row justify-content-center"><h3>Tarif: <%= @event.price%> $</h3> 
     </label>
    </div>
    <%= link_to "Confirmation et paiement", new_charge_path(id: @event.id), class: "mt-2 btn btn-dark text-light text-center" %>
</div>

  

  
      </div>
    </div>
   </div>
  </div>
 </div>
</div> 
    </div>
        </div>
      </div>
    </div>
    

<div class="row justify-content-center">
  <div class="container-fluid row justify-content-center">
    <%= link_to "Retour", :back %>
  </div>

app/views/charges/create.html.erb
<h2>Merci pour le paiement !</h2>

<%= current_user.id %></br>
<%= @customer_id %></br>
<%= @event.id %>

  <%= form_tag attendances_path, method: "post" do %>

    <%= hidden_field_tag :user_id, current_user.id %>
    <%= hidden_field_tag :event_id, @event.id %>
    <%= hidden_field_tag :customer_id, @customer_id %>

    <%= submit_tag "Confirmer le paiement", class: "btn btn-dark text-light" %>
    
  <% end %>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= @event.price %>€</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount=<%= @event.price * 100 %>
          data-locale="auto"></script>

<%= hidden_field_tag :id, @event.id %>
<% end %>

app/views/events/edit.html.erb
<div class="col-md-6 offset-md-3">

  <div class="row justify-content-center"> 
   <h3 class="texte-bienvenue mt-5">Modifie ton event</h3>
  </div>

 <div class="container">
  <div class="card border-0 shadow my-5">
    <div class="card-body p-5">
    <div class="row justify-content-center">

 
 <div class="container-fluid text-center">
  <div class="container-fluid">
    <%= form_for(:events,  url:(event_path), action: 'update', method: :patch) do |f| %>
  

      <div class="field">
        <%= f.label "Titre" %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: :title, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Description" %> <br />
        <%= f.text_area :description, autocomplete: :description, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Localisation" %> <br />
        <%= f.text_field :location, autocomplete: :location, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Date" %> <br />
        <%= f.datetime_field :start_date, autocomplete: :start_date, class: "form-control" %>
      </div><br />
      
      <div class="field">
        <%= f.label "Durée en minute"%> <br />
        <%= f.text_field :duration, placeholder: "Doit finir par 0 ou 5", class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Prix" %> <br />
        <%= f.number_field :price, autocomplete: :price, class: "form-control" %>
      </div><br />

      <div class="actions">
        <%= f.submit "Modifier ton évènement", class: "btn btn-sm btn-primary" %>
      </div>
      
    <% end %>
  </div>
  </div>
  
</div> 
</div>
</div>
<div class="row justify-content-center"> 
    <%= link_to "Retour", :back %>
</div>
</div>
</div>

app/views/events/index.html.erb
<!DOCTYPE html>
<html>
  <head>
 

  </head>

  <body>
 
 <%= render 'layouts/ban'%>


<!-- Page Content -->


<%= render 'layouts/cardevent'%>






<!-- Bootstrap core JavaScript -->

</body>
</html>

app/views/events/new.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="stylesheet" href="application.css" />
  </head>

<body>

<%= render 'layouts/newevent'%>

</body>

</html>

app/views/events/show.html.erb
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="application.css" />

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body>

<!-- <br>
<div class="row justify-content-center">
 <h3>Page de l'évènement<h3>
 </div>
<br>


<div class="jumbotron bg_img text-dark">
  <div class="row justify-content-center">
<div class="card" style="width: 30rem;">

 <%= image_tag @events.avatar, alt: 'avatar' if @events.avatar.attached? %>


<%= form_tag event_avatars_path(@events.id), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>

 
  <div class="card-header">
   ID : <%= @events.id %>
  </div>
  <ul class="list-group list-group-flush">
  <li class="list-group-item">Créé par : <%= @events.admin.first_name %></li>
    <li class="list-group-item">Nom : <%= @events.title %></li>
    <li class="list-group-item">Localisation : <%= @events.location %> </li>
    <li class="list-group-item">Date: <%= @events.start_date %> </li>
    <li class="list-group-item">Description : <%= @events.description%> </li>
    <li class="list-group-item">Participants : <%= @events.attendances.count%> </li>
    <li class="list-group-item">Prix : <%= @events.price%> €</li>
  
    <%= link_to "Participer", new_attendance_path(id: @events.id) , class:"btn btn-outline-dark" %> 
    <% if current_user == @events.admin %>
     <%= link_to "Editer", edit_event_path(id: @events.id) , class:"btn btn-indo" %> 
    <% end %>
  </ul>
</div>
</div>
</div> -->


<%= render 'layouts/eventinfo'%>

</body>
</html>

app/views/layouts/_ban.html.erb
<!DOCTYPE html>
<html>
<head>



<link rel="stylesheet" href="application.css" />
</head>
<body>

  <div class="jumbotron">
    <h1 class="display-3">Bienvenue sur EventBrite !</h1>
    <p class="lead">Le leader de la création d'évènement</p>
    <hr class="my-4">
    <p>Prêt à te lancer ?</p>
     <% if current_user %>    
          <p><a class="btn btn-primary btn-lg" role="button"<%= link_to "Créer un event", new_event_path %></a></p>
           <% else %>
           <p><a class="btn btn-primary btn-lg" role="button"<%= link_to "Créer un event", new_user_session_path %></a></p>
         <% end %>
  </div>


</body>
</html>  

app/views/layouts/_card.html.erb
<!DOCTYPE html>
<html>
<head>


<link rel="stylesheet" href="application.css" />
</head>
<body>

  

<div class="row justify-content-center">
 
<div class="card text-white mb-3" style="max-width: 20rem;">
  <img class="card-img-top" src="https://images.unsplash.com/photo-1492633423870-43d1cd2775eb?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1050&q=80" alt="Card image cap">

  <div class="card-header bg-primary">Mon profil</div>

  <a href="#" class="list-group-item list-group-item-action">ID : <%= @users.id %>
  </a>
  <a href="#" class="list-group-item list-group-item-action">Email : <%= @users.email %>
  </a>
  <a href="#" class="list-group-item list-group-item-action">Prénom : <%= @users.first_name %>
  </a>
  <a href="#" class="list-group-item list-group-item-action">Nom :  <%= @users.last_name %>
  </a>
  <a href="#" class="list-group-item list-group-item-action">Description : <%= @users.description%>
  </a>
   <%= link_to "Éditer ton profil", edit_user_path , class:"btn btn-outline-dark" %> 
  </div>
 
</div>
</div>


</body>
</html>

app/views/layouts/_eventinfo.html.erb
<!DOCTYPE html>
<html>
<head>

<link rel="stylesheet" href="application.css" />

<link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>

</head>
<body>

<div class="container">
  <div class="shadow-sm p-3 mb-5 border border-primary rounded">
  <div class="row">
    <div class="col-8">
    <div class="avatar" height="150px">
<div class="row justify-content-center">
 <%= image_tag @events.avatar, alt: 'avatar' if @events.avatar.attached? %>
<%= form_tag event_avatars_path(@events.id), multipart: true do %>
  <%= file_field_tag :avatar %>
  <%= submit_tag "mettre à jour" %>
<% end %>
</div>
</div>       
       
    </div>
    <div class="col-4"> 
      
        
        <div class="card text-white mb-3">
          
        
          <div class="card-header bg-primary">Informations évènement</div>
        
          <a href="#" class="list-group-item list-group-item-action">ID : <%= @events.id %>
          </a>
          <a href="#" class="list-group-item list-group-item-action">Contact : <%= @events.admin.email %> 
          </a>
          <a href="#" class="list-group-item list-group-item-action">Nom : <%= @events.title %>
          </a>
          <a href="#" class="list-group-item list-group-item-action">Créé par : <%= @events.admin.first_name %> <%= @events.admin.last_name %>
          </a>
          
          
          <a href="#" class="list-group-item list-group-item-action">Localisation : <%= @events.location %>
          </a>
          <a href="#" class="list-group-item list-group-item-action">Date : <%= @events.start_date %>
          </a>
          <a href="#" class="list-group-item list-group-item-action">Participants : <%= @events.attendances.count%>
          </a>
          <a href="#" class="list-group-item list-group-item-action">Prix : <%= @events.price%> €
          </a>
          </div>
          </div>
    </div>

    <div class="row justify-content-center ">
         <%= link_to "Participer", new_attendance_path(id: @events.id) , class:"btn btn-outline-primary" %> 
    <% if current_user == @events.admin %>
     <%= link_to "Editer", edit_event_path(id: @events.id) , class:"btn btn-indo" %> 
    <% end %>
    </div>

    <br>
    <br>

    <div class="row">
      <div class="col-8">
        <div class="list-group">
          <a href="#" class=" list-group-item-action flex-column align-items-start text-primary">
            <div class="d-flex w-100 justify-content-between">
              <h5 class="mb-1">Description</h5>
              
            </div>
            <p class="mb-1"><%= @events.description%></p>
            
          </a>
        </div>
      </div>


      <div class="col-4">
        <div class="card text-white mb-3">
              
            
          <div class="card-header bg-primary">Informations complémentaires</div>
        
          <a href="#" class="list-group-item list-group-item-action">Heure :
          </a>
          <a href="#" class="list-group-item list-group-item-action">Tenue : Décontracté
          </a>
          </div>
        </div>
    

    </div>

    

    <div class="row justify-content-center">
      <div class="logo">
      <i class="fab fa-facebook-square"></i>
      <i class="fab fa-twitter-square"></i>
      <i class="fab fa-whatsapp-square"></i>

</div>
    </div>

    </div>

  </div>







</body>
</html>  

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
<head>
 


<link rel="stylesheet" href="application.css" />
</head>
<body>




<footer>
    <p>By Timoo</p>
</footer>


</body>
</html>

app/views/layouts/_formlogin.html.erb
<!DOCTYPE html>
<html>
<head>


</head>
<body>
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for resource, as: resource_name, url: session_path(resource_name), html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Log in</h1>
        <div class="form-group">
          <%= f.label :email, "Email" %><br />
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
         <br />
          <%= f.password_field :password, autocomplete: "current-password", class: "form-control" %>
        </div>
 
<% if devise_mapping.rememberable? %>
    <div class="field">
      <%= f.check_box :remember_me %>
      <%= f.label :remember_me %>
    </div>
  <% end %>

        <div class="actions mt-5">
          <%= f.submit "Log in", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>

  


</body>
</html>  

app/views/layouts/_formsignup.html.erb
<!DOCTYPE html>
<html>
<head>
<body>

<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <br><br><br>
      <%= form_for resource, as: resource_name, url: registration_path(resource_name), html: { class: "form-signin mt-3" } do |f| %>
        <h1 class="h3 mb-3 font-weight-normal text-center">Sign up</h1>
        <%= devise_error_messages! %>
        
        <div class="form-group">
          <%= f.label :email, "Email" %><br/>
          <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password %>
          <% if @minimum_password_length %>
          <em>(<%= @minimum_password_length %> characters minimum)</em>
          <% end %><br />
          <%= f.password_field :password, autocomplete: "new-password", class: "form-control" %>
        </div>
        <div class="form-group">
          <%= f.label :password_confirmation %><br>
          <%= f.password_field :password_confirmation, autocomplete: "new-password", class: "form-control" %>
        </div>
        <div class="actions mt-5">
          <%= f.submit "Sign up", class: "btn btn-lg btn-primary btn-block" %>
        </div>
      <% end %>
      <%= render "devise/shared/links" %>
    </div>
  </div>
</div>



</body>


</html>

app/views/layouts/_navbar.html.erb
<!DOCTYPE html>
<html>
<head>



<link rel="stylesheet" href="application.css" />
<script>

  var _gaq = _gaq || [];
   _gaq.push(['_setAccount', 'UA-23019901-1']);
   _gaq.push(['_setDomainName', "bootswatch.com"]);
     _gaq.push(['_setAllowLinker', true]);
   _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

 </script>
</head>

<body>


<nav class="navbar navbar-expand-lg navbar-dark fixed-top bg-primary">
  <a class="navbar-brand" href="/">EventBrite</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor01">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <% if current_user %>    
              <%= link_to "Créer un event", new_event_path, class: 'nav-link' %>
        </li>
        <% else %>
         <% end %>
    
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <% if current_user %>            
        Mon profil
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="<%= user_path(current_user.id) %>">Mon profil</a>
          <a class="dropdown-item" href="<%= destroy_user_session_path %>" data-method="DELETE">Se deconnecter</a>
          
          <% else %>
          Se connecter/S'inscrire
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="#">
           <%= link_to "S'inscrire", new_user_registration_path %> </a>
          <a class="dropdown-item" href="#">
          <%= link_to "Se connecter", new_user_session_path %> </a>
          <% end %>
  
        </div>
      </li>
    </ul>

    
  </div>
  
</nav>

<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</body>

</html>

app/views/layouts/_newevent.html.erb
<!DOCTYPE html>
<html>
  <head>
<link rel="stylesheet" href="application.css" />
  </head>

<body>

<br>
<br>
<br>

<div class="col-md-6 offset-md-3">

  <div class="row justify-content-center"> 
   <h3 class="texte-bienvenue mt-5">Créer un nouvel event bright</h3>
  </div>
  <br>
  
<div class="jumbotron">
  <div class="row justify-content-center">
    <div class="card" style="width: 30rem;">
      <div class="card-header">

 <div class="container">
    <div class="card-body p-1">
     <div class="row justify-content-center">

 
 <div class="container-fluid text-center">
  <div class="container-fluid">
    <%= form_for(:events,  url:(events_path), action: 'create', method: :post) do |f| %>
      <div class="field">
        <%= f.hidden_field :admin_id, :value => current_user.id %>
      </div><br />

      <div class="field">
        <%= f.label "Titre" %><br />
        <%= f.text_field :title, autofocus: true, autocomplete: :title, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Description" %> <br />
        <%= f.text_area :description, placeholder: "20 caractères minimum", autocomplete: :description, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Localisation" %> <br />
        <%= f.text_field :location, autocomplete: :location, class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Date" %> <br />
        <%= f.datetime_field :start_date, autocomplete: :start_date, class: "form-control" %>
      </div><br />
      
      <div class="field">
        <%= f.label "Durée en minute"%> <br />
        <%= f.text_field :duration, placeholder: "doit finir par 0 ou 5", class: "form-control" %>
      </div><br />

      <div class="field">
        <%= f.label "Prix" %> <br />
        <%= f.number_field :price, autocomplete: :price, class: "form-control" %>
      </div><br />

<div class="actions">
          <%= f.submit "Créer mon event !", class:"btn btn-dark btn-sm" %>
      </div>
    </div>
   </div>
 
  
     </div> 
    </div>
   </div>
  </div>
 </div> 
 </div>
   </div>
  </div>
 

<div class="row justify-content-center"> 
  <%= link_to "Retour", :back %>
</div>

<% end %>

</body>

</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>